### PR TITLE
Sertxd table extension

### PR DESCRIPTION
**Pull request by jgOhYeah**
Hi Patrick,
I am not sure if you would want to merge this as it is a non standard extension to the preprocessor, but I thought make a pull request just in case you thought it could pass :).

I have been working on some projects with a lot of code that have been running out of program space. I thought it would be nice to store strings in table memory or eeprom, but didn’t want to spend a lot of time keeping track of string lengths and memory locations every time I changed a string. Instead, I ended up spending significantly more time on this extension that will do all of that automatically :).

This extension must be enabled by calling the preprocessor with a `--tablesertxd` flag. Parameters and various behaviours can be set using `#define`s as per [this documentation](https://github.com/jgOhYeah/PicaxePreprocess/tree/sertxdTableExtension#table-sertxd-extension). To print a string, the directive `;#sertxd` is used, with hopefully the same syntax as the `sertxd` command. Starting the directive with `;` should mean that any preprocessor not using this extension will treat this as a comment and will still compile, leaving serial printing out.

An example of usage and output can be found [here](Hi Patrick,
I am not sure if you would want to merge this as it is a non standard extension to the preprocessor, but I thought make a pull request just in case you thought it could pass :).

I have been working on some projects with a lot of code that have been running out of program space. I thought it would be nice to store strings in table memory or eeprom, but didn’t want to spend a lot of time keeping track of string lengths and memory locations every time I changed a string. Instead, I ended up spending significantly more time on this extension that will do all of that automatically :).

This extension must be enabled by calling the preprocessor with a `--tablesertxd` flag. Parameters and various behaviours can be set using `#define`s as per [this documentation](https://github.com/jgOhYeah/PicaxePreprocess/tree/sertxdTableExtension#table-sertxd-extension). To print a string, the directive `;#sertxd` is used, with hopefully the same syntax as the `sertxd` command. Starting the directive with `;` should mean that any preprocessor not using this extension will treat this as a comment and will still compile, leaving serial printing out.

An example of usage and output can be found [here](https://github.com/jgOhYeah/PicaxePreprocess/tree/sertxdTableExtension#table-sertxd-extension-usage-example).

Regards
Jotham)

### CODE REVIEW

**Comment by Patronics** [comment]
Sorry for the very late response, but I just pushed a few tweaks to detect when a variable is passed in in the form `w0`, `b5`, `bit12`, etc. Symbols that correspond to variable names, or other special variables like `time` still slip through undetected. I also added detection for when the table/eeprom storage is full, and warn the user about that. Once you test and confirm my changes don't break anything for you, I'll merge it in :).

**Comment by jgOhYeah** [comment]
Apologies for the delay at having a look at this. They are some sensible changes to improve usability. I have realised that I have scrambled the commit history and spread things over a couple of branches, so have had an attempt at untangling things and merging the important bits into this branch and sorting things out ready to merge to master.  I have tested things and everything seems to work as expected.

**Comment by Patronics** [comment]
I'm working on a project where this can come in handy, but with one additional feature that hopefully I'll get a chance to implement sometime soon (or if you happen to have a chance to do so before I do and are so inclined, that'd be very appreciated!). My thinking is that for use with serial displays (such as the AXE133 and many similar devices), an option to replace the `sertxd` command with arbitrary other commands (in my case `serout disp, dispbaud,` (where I already have disp and dispbaud defined as symbols, though that's not a requirement of course, it could use any similar hardcoded values such as `serout C.0 N4800,` or `hi2cout `), would be a very useful extension!
I'm thinking either adding it as an additional command (`;#tableserout`, `;#tablehi2cout`, etc) could be good to allow potential mixing and matching of options, but it could also be implemented somewhat more simply with another #DEFINE such as `#DEFINE TABLE_SERTXD_CUSTOM_COMMAND "serout C.0 N4800"` or as an additional command-line argument such as `--tablesertxdcustomcommand "serout C.0 N4800"`. 

Interested in your thoughts on this!

@jgOhYeah  Let me know if you want to try to tackle this before I do, since you are more familiar with the existing tablesertxd implementation. If not I'll hopefully get around to it soon :)

**Comment by Patronics** [comment]
I just pushed an implementation that should work for serout, though I haven't tested it on physical hardware yet. It should be relatively simple to mimic those changes to add the other serial output commands that are likely to benefit from it, such as hserout, hi2cout, hspiout, etc. 

Though it still may be advantageous to have another variant where the output command is determined on a per-command basis, or allowing duplicates of different commands with the same configuration, which would enable, for example, serout to multiple pins in the same program, or i2c out to multiple peripherals (though we could also just not specify a peripheral address, instead leaving that to be done before invoking the command, to solve the i2c case in particular).

**Comment by Patronics** [comment]
So this seems to work well in my tests. It could certainly still use a more generic option (or a few more specific ones) for other serial communications options, which should be relatively simple to add by mirroring the changes in commit #05997dd, so I think I'm ready to merge this in, and will add those changes later (or another pull request to do so is welcome). Thanks again for the contribution @jgOhYeah!

**Comment by jgOhYeah** [comment]
Apologies for the delay getting back. Expanding this to other commands is a good idea I hadn't thought of. I have had a look and test in comparison with the original version of `;#sertxd` and it is byte compatible and the updates look good.

**Pull request merged**
